# Site settings
baseURL = ""
languageCode = "en-US"
title = "Giacomo Sepe"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-134667709-2"

# Copyright
copyright = "&copy;2021 Giacomo"

[params]

  # Metadata for search engines and social sharing
  author = "Giacomo Sepe"
  description = "Consulente e manager specializzato nel finanziamento e nella gestione di progetti di trasformazione digitale."
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "uploads/images/favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "uploads/images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "uploads/videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Contatti"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:giacomo@giacomosepe.com"

      [[params.links.list1.link]]
        text = "Ianus Capital"
        url = "https://ianuscapital.com"

      [[params.links.list1.link]]
        text = ""
        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "LinkedIn"
        url = "https://www.linkedin.com/in/giacomosepe/"

      [[params.links.list2.link]]
        text = "Angel List"
        url = "https://angel.co/u/giacomosepe"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://www.instagram.com/giachisz"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Foto"

      [[params.links.list3.link]]
        text = "Le mie foto"
        url = "foto.giacomosepe.com"

      [[params.links.list3.link]]
        text = "Saul"
        url = "http://saulleiterfoundation.org/"

      [[params.links.list3.link]]
        text = ""
        url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
