backend: 
  name: git-gateway
  branch: master

media_folder: "static/uploads"
public_folder: "uploads"

collections:
  - name: "main"
    label: "Main"
    folder: "content/"
    create: true
    slug: {{ slug }}
    fields:
      - {label: "Title", name: "title", wiget: "string", required: false }